-- Supabase bootstrap for Vizare
--
-- This schema supports the current Flutter app structure:
-- - user profiles / roles
-- - property listings
-- - property images
-- - favorites
-- - inquiries
-- - support tickets
-- - storage buckets for avatars and property assets
--
-- Vercel compatibility routes access tables with the service-role key.
-- Flutter authenticates with Supabase and sends its access token to those routes.

create extension if not exists pgcrypto;

-- ------------------------------------------------------------
-- Types
-- ------------------------------------------------------------

do $$ begin
  create type public.user_role as enum ('homebuyer', 'homeowner', 'admin');
exception
  when duplicate_object then null;
end $$;

do $$ begin
  create type public.property_status as enum ('pending', 'approved', 'rejected', 'sold', 'draft');
exception
  when duplicate_object then null;
end $$;

do $$ begin
  create type public.ticket_status as enum ('new', 'open', 'in_progress', 'resolved', 'closed');
exception
  when duplicate_object then null;
end $$;

-- ------------------------------------------------------------
-- Tables
-- ------------------------------------------------------------

create table if not exists public.profiles (
  id bigint generated by default as identity primary key,
  auth_user_id uuid unique references auth.users(id) on delete cascade,
  email text not null unique,
  full_name text,
  phone text,
  role public.user_role not null default 'homebuyer',
  profile_pic text,
  has_password boolean not null default false,
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.profiles
  add column if not exists auth_user_id uuid unique references auth.users(id) on delete cascade;
alter table public.profiles add column if not exists phone text;

create table if not exists public.properties (
  id bigint generated by default as identity primary key,
  homeowner_id bigint not null references public.profiles(id) on delete cascade,
  name text not null,
  location text not null,
  price text not null,
  description text not null,
  image_path text not null,
  model_path text not null default '',
  is_featured boolean not null default false,
  status public.property_status not null default 'pending',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.property_images (
  id bigint generated by default as identity primary key,
  property_id bigint not null references public.properties(id) on delete cascade,
  image_url text not null,
  sort_order integer not null default 0,
  created_at timestamptz not null default now()
);

create table if not exists public.favorites (
  id bigint generated by default as identity primary key,
  profile_id bigint not null references public.profiles(id) on delete cascade,
  property_id bigint not null references public.properties(id) on delete cascade,
  created_at timestamptz not null default now(),
  unique (profile_id, property_id)
);

create table if not exists public.inquiries (
  id bigint generated by default as identity primary key,
  homeowner_id bigint not null references public.profiles(id) on delete cascade,
  property_id bigint not null references public.properties(id) on delete cascade,
  property_name text not null,
  property_image text,
  buyer_email text not null,
  message text not null,
  is_read boolean not null default false,
  created_at timestamptz not null default now()
);

create table if not exists public.support_tickets (
  id bigint generated by default as identity primary key,
  profile_id bigint references public.profiles(id) on delete set null,
  user_email text not null,
  subject text not null,
  description text not null,
  attachment_urls jsonb not null default '[]'::jsonb,
  status public.ticket_status not null default 'new',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.notification_preferences (
  profile_id bigint primary key references public.profiles(id) on delete cascade,
  push_notifications boolean not null default false,
  email_notifications boolean not null default false,
  in_app_notifications boolean not null default true,
  updated_at timestamptz not null default now()
);

-- ------------------------------------------------------------
-- Updated-at trigger
-- ------------------------------------------------------------

create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists set_profiles_updated_at on public.profiles;
create trigger set_profiles_updated_at
before update on public.profiles
for each row execute function public.set_updated_at();

drop trigger if exists set_properties_updated_at on public.properties;
create trigger set_properties_updated_at
before update on public.properties
for each row execute function public.set_updated_at();

drop trigger if exists set_support_tickets_updated_at on public.support_tickets;
create trigger set_support_tickets_updated_at
before update on public.support_tickets
for each row execute function public.set_updated_at();

drop trigger if exists set_notification_preferences_updated_at on public.notification_preferences;
create trigger set_notification_preferences_updated_at
before update on public.notification_preferences
for each row execute function public.set_updated_at();

create or replace function public.handle_new_auth_user()
returns trigger
language plpgsql
security definer set search_path = ''
as $$
begin
  insert into public.profiles (
    auth_user_id, email, full_name, role, has_password
  )
  values (
    new.id,
    new.email,
    coalesce(new.raw_user_meta_data ->> 'full_name', new.raw_user_meta_data ->> 'name', 'User'),
    case new.raw_user_meta_data ->> 'role'
      when 'homeowner' then 'homeowner'::public.user_role
      when 'admin' then 'admin'::public.user_role
      else 'homebuyer'::public.user_role
    end,
    coalesce((new.raw_user_meta_data ->> 'has_password')::boolean, false)
  )
  on conflict (email) do update
  set auth_user_id = excluded.auth_user_id,
      full_name = coalesce(public.profiles.full_name, excluded.full_name),
      updated_at = now();
  return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
after insert on auth.users
for each row execute function public.handle_new_auth_user();

-- ------------------------------------------------------------
-- Storage
-- ------------------------------------------------------------

insert into storage.buckets (id, name, public)
values
  ('avatars', 'avatars', true),
  ('property-assets', 'property-assets', true),
  ('support-attachments', 'support-attachments', false)
on conflict (id) do update
set public = excluded.public;

-- Public read access for uploaded assets.
drop policy if exists "Public read avatars" on storage.objects;
create policy "Public read avatars"
on storage.objects
for select
using (bucket_id = 'avatars');

drop policy if exists "Public read property assets" on storage.objects;
create policy "Public read property assets"
on storage.objects
for select
using (bucket_id = 'property-assets');

drop policy if exists "Authenticated read support attachments" on storage.objects;
create policy "Authenticated read support attachments"
on storage.objects
for select
to authenticated
using (
  bucket_id = 'support-attachments'
  and (storage.foldername(name))[1] = (select auth.uid()::text)
);

-- Users write only inside a folder named after their Supabase user id.
drop policy if exists "Anon upload avatars" on storage.objects;
drop policy if exists "Authenticated upload avatars" on storage.objects;
create policy "Authenticated upload avatars"
on storage.objects
for insert
to authenticated
with check (
  bucket_id = 'avatars'
  and (storage.foldername(name))[1] = (select auth.uid()::text)
);

drop policy if exists "Anon update avatars" on storage.objects;
drop policy if exists "Authenticated update avatars" on storage.objects;
create policy "Authenticated update avatars"
on storage.objects
for update
to authenticated
using (
  bucket_id = 'avatars'
  and (storage.foldername(name))[1] = (select auth.uid()::text)
)
with check (
  bucket_id = 'avatars'
  and (storage.foldername(name))[1] = (select auth.uid()::text)
);

drop policy if exists "Anon delete avatars" on storage.objects;
drop policy if exists "Authenticated delete avatars" on storage.objects;
create policy "Authenticated delete avatars"
on storage.objects
for delete
to authenticated
using (
  bucket_id = 'avatars'
  and (storage.foldername(name))[1] = (select auth.uid()::text)
);

drop policy if exists "Anon upload property assets" on storage.objects;
drop policy if exists "Authenticated upload property assets" on storage.objects;
create policy "Authenticated upload property assets"
on storage.objects
for insert
to authenticated
with check (
  bucket_id = 'property-assets'
  and (storage.foldername(name))[1] = (select auth.uid()::text)
);

drop policy if exists "Anon update property assets" on storage.objects;
drop policy if exists "Authenticated update property assets" on storage.objects;
create policy "Authenticated update property assets"
on storage.objects
for update
to authenticated
using (
  bucket_id = 'property-assets'
  and (storage.foldername(name))[1] = (select auth.uid()::text)
)
with check (
  bucket_id = 'property-assets'
  and (storage.foldername(name))[1] = (select auth.uid()::text)
);

drop policy if exists "Anon delete property assets" on storage.objects;
drop policy if exists "Authenticated delete property assets" on storage.objects;
create policy "Authenticated delete property assets"
on storage.objects
for delete
to authenticated
using (
  bucket_id = 'property-assets'
  and (storage.foldername(name))[1] = (select auth.uid()::text)
);

drop policy if exists "Authenticated upload support attachments" on storage.objects;
create policy "Authenticated upload support attachments"
on storage.objects
for insert
to authenticated
with check (
  bucket_id = 'support-attachments'
  and (storage.foldername(name))[1] = (select auth.uid()::text)
);

drop policy if exists "Authenticated delete support attachments" on storage.objects;
create policy "Authenticated delete support attachments"
on storage.objects
for delete
to authenticated
using (
  bucket_id = 'support-attachments'
  and (storage.foldername(name))[1] = (select auth.uid()::text)
);

-- ------------------------------------------------------------
-- RLS
-- ------------------------------------------------------------

alter table public.profiles enable row level security;
alter table public.properties enable row level security;
alter table public.property_images enable row level security;
alter table public.favorites enable row level security;
alter table public.inquiries enable row level security;
alter table public.support_tickets enable row level security;
alter table public.notification_preferences enable row level security;

drop policy if exists "Profiles are readable" on public.profiles;
drop policy if exists "Profiles are insertable" on public.profiles;
drop policy if exists "Profiles are updatable" on public.profiles;
drop policy if exists "Properties are readable" on public.properties;
drop policy if exists "Properties are insertable" on public.properties;
drop policy if exists "Properties are updatable" on public.properties;
drop policy if exists "Properties are deletable" on public.properties;
drop policy if exists "Property images are readable" on public.property_images;
drop policy if exists "Property images are insertable" on public.property_images;
drop policy if exists "Property images are updatable" on public.property_images;
drop policy if exists "Property images are deletable" on public.property_images;
drop policy if exists "Favorites are readable" on public.favorites;
drop policy if exists "Favorites are insertable" on public.favorites;
drop policy if exists "Favorites are deletable" on public.favorites;
drop policy if exists "Inquiries are readable" on public.inquiries;
drop policy if exists "Inquiries are insertable" on public.inquiries;
drop policy if exists "Support tickets are readable" on public.support_tickets;
drop policy if exists "Support tickets are insertable" on public.support_tickets;
drop policy if exists "Notification preferences are readable" on public.notification_preferences;
drop policy if exists "Notification preferences are insertable" on public.notification_preferences;
drop policy if exists "Notification preferences are updatable" on public.notification_preferences;
