name: untitled
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  google_sign_in: ^6.2.1
  firebase_auth: ^5.3.1
  firebase_core: ^3.6.0
  cloud_firestore: ^5.4.0
  firebase_storage: ^12.3.0
  google_maps_flutter: ^2.6.1
  geocoding: ^4.0.0
  file_picker: ^10.3.6
  path: ^1.9.0
  intl: ^0.19.0
  model_viewer_plus: ^1.7.0
  shared_preferences: ^2.2.3
  http: ^1.6.0
  logger: ^2.0.2
  photo_view: ^0.15.0
  url_launcher: ^6.3.2
  flutter_dotenv: ^6.0.0
  supabase_flutter: ^2.15.4
  google_fonts: ^6.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.14.4
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/images/house/
    - .env
  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter_28pt-Thin.ttf
          weight: 100
        - asset: assets/fonts/Inter_28pt-ThinItalic.ttf
          weight: 100
          style: italic
        - asset: assets/fonts/Inter_28pt-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/Inter_28pt-ExtraLightItalic.ttf
          weight: 200
          style: italic
        - asset: assets/fonts/Inter_28pt-Light.ttf
          weight: 300
        - asset: assets/fonts/Inter_28pt-LightItalic.ttf
          weight: 300
          style: italic
        - asset: assets/fonts/Inter_28pt-Regular.ttf
          weight: 400
        - asset: assets/fonts/Inter_28pt-Italic.ttf
          weight: 400
          style: italic
        - asset: assets/fonts/Inter_28pt-Medium.ttf
          weight: 500
        - asset: assets/fonts/Inter_28pt-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: assets/fonts/Inter_28pt-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Inter_28pt-SemiBoldItalic.ttf
          weight: 600
          style: italic
        - asset: assets/fonts/Inter_28pt-Bold.ttf
          weight: 700
        - asset: assets/fonts/Inter_28pt-BoldItalic.ttf
          weight: 700
          style: italic
        - asset: assets/fonts/Inter_28pt-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Inter_28pt-ExtraBoldItalic.ttf
          weight: 800
          style: italic
        - asset: assets/fonts/Inter_28pt-Black.ttf
          weight: 900
        - asset: assets/fonts/Inter_28pt-BlackItalic.ttf
          weight: 900
          style: italic

    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Thin.ttf
          weight: 100
        - asset: assets/fonts/Poppins-ThinItalic.ttf
          weight: 100
          style: italic
        - asset: assets/fonts/Poppins-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/Poppins-ExtraLightItalic.ttf
          weight: 200
          style: italic
        - asset: assets/fonts/Poppins-Light.ttf
          weight: 300
        - asset: assets/fonts/Poppins-LightItalic.ttf
          weight: 300
          style: italic
        - asset: assets/fonts/Poppins-Regular.ttf
          weight: 400
        - asset: assets/fonts/Poppins-Italic.ttf
          weight: 400
          style: italic
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-SemiBoldItalic.ttf
          weight: 600
          style: italic
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700
        - asset: assets/fonts/Poppins-BoldItalic.ttf
          weight: 700
          style: italic
        - asset: assets/fonts/Poppins-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Poppins-ExtraBoldItalic.ttf
          weight: 800
          style: italic
        - asset: assets/fonts/Poppins-Black.ttf
          weight: 900
        - asset: assets/fonts/Poppins-BlackItalic.ttf
          weight: 900
          style: italic

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icon/app_icon.png"
