-- Migration: Property Types Table, Property Column & Backfill

-- 1. Create property_types table
create table if not exists public.property_types (
  id bigint generated by default as identity primary key,
  name text not null unique,
  icon text not null default 'home_work_rounded',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

-- Enable RLS
alter table public.property_types enable row level security;

-- Policies for property_types: Anyone can read, only admin can insert/update/delete
drop policy if exists "Anyone can read property types" on public.property_types;
create policy "Anyone can read property types"
  on public.property_types
  for select
  using (true);

drop policy if exists "Admins can manage property types" on public.property_types;
create policy "Admins can manage property types"
  on public.property_types
  for all
  using (
    exists (
      select 1 from public.profiles
      where profiles.auth_user_id = auth.uid()
        and profiles.role = 'admin'
    )
  );

-- Trigger for updated_at
drop trigger if exists set_property_types_updated_at on public.property_types;
create trigger set_property_types_updated_at
before update on public.property_types
for each row execute function public.set_updated_at();

-- 2. Seed initial property types if table is empty
insert into public.property_types (name, icon)
values
  ('Apartment / Flat', 'apartment_rounded'),
  ('Condominium', 'domain_rounded'),
  ('Luxury Villa', 'villa_rounded'),
  ('Duplex / Penthouse', 'roofing_rounded'),
  ('Detached House / Bungalow', 'holiday_village_rounded'),
  ('Terraced House / Townhouse', 'home_work_rounded'),
  ('Serviced Residence', 'location_city_rounded'),
  ('Loft', 'storefront_rounded'),
  ('Studio Unit', 'single_bed_rounded'),
  ('Commercial Property', 'business_rounded'),
  ('Modern Luxury', 'stars_rounded')
on conflict (name) do nothing;

-- 3. Add property_type column to properties table
alter table public.properties
  add column if not exists property_type text not null default 'Modern Luxury';

-- 4. Backfill existing properties based on name / description keywords so none remain generic default
update public.properties
set property_type = case
  when lower(name) like '%villa%' or lower(description) like '%villa%' then 'Luxury Villa'
  when lower(name) like '%penthouse%' or lower(description) like '%penthouse%' or lower(name) like '%sky%' then 'Duplex / Penthouse'
  when lower(name) like '%condo%' or lower(name) like '%residence%' or lower(description) like '%condo%' then 'Condominium'
  when lower(name) like '%bungalow%' or lower(name) like '%mansion%' or lower(name) like '%estate%' then 'Detached House / Bungalow'
  when lower(name) like '%townhouse%' or lower(name) like '%terrace%' then 'Terraced House / Townhouse'
  when lower(name) like '%loft%' then 'Loft'
  when lower(name) like '%studio%' then 'Studio Unit'
  when lower(name) like '%apartment%' or lower(name) like '%flat%' then 'Apartment / Flat'
  else 'Modern Luxury'
end
where property_type is null or property_type = 'Modern Luxury';
