-- Supabase bootstrap for Vizare
--
-- This schema supports the current Flutter app structure:
-- - user profiles / roles
-- - property listings
-- - property images
-- - favorites
-- - inquiries
-- - support tickets
-- - storage buckets for avatars and property assets
--
-- Vercel compatibility routes access tables with the service-role key.
-- Flutter authenticates with Supabase and sends its access token to those routes.

create extension if not exists pgcrypto;

-- ------------------------------------------------------------
-- Types
-- ------------------------------------------------------------

do $$ begin
  create type public.user_role as enum ('homebuyer', 'homeowner', 'admin');
exception
  when duplicate_object then null;
end $$;

do $$ begin
  create type public.property_status as enum ('pending', 'approved', 'rejected', 'sold', 'draft');
exception
  when duplicate_object then null;
end $$;

do $$ begin
  create type public.ticket_status as enum ('new', 'open', 'in_progress', 'resolved', 'closed');
exception
  when duplicate_object then null;
end $$;

-- ------------------------------------------------------------
-- Tables
-- ------------------------------------------------------------

create table if not exists public.profiles (
  id bigint generated by default as identity primary key,
  auth_user_id uuid unique references auth.users(id) on delete cascade,
  email text not null unique,
  full_name text,
  phone text,
  role public.user_role not null default 'homebuyer',
  profile_pic text,
  has_password boolean not null default false,
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.profiles
  add column if not exists auth_user_id uuid unique references auth.users(id) on delete cascade;
alter table public.profiles add column if not exists phone text;
alter table public.profiles add column if not exists consent_terms_at timestamptz;
alter table public.profiles add column if not exists consent_privacy_at timestamptz;
alter table public.profiles add column if not exists consent_version text;

create table if not exists public.properties (
  id bigint generated by default as identity primary key,
  homeowner_id bigint not null references public.profiles(id) on delete cascade,
  name text not null,
  location text not null,
  price double precision not null default 0.0,
  description text not null,
  image_path text not null,
  model_path text not null default '',
  is_featured boolean not null default false,
  status public.property_status not null default 'pending',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.property_images (
  id bigint generated by default as identity primary key,
  property_id bigint not null references public.properties(id) on delete cascade,
  image_url text not null,
  sort_order integer not null default 0,
  created_at timestamptz not null default now()
);

create table if not exists public.favorites (
  id bigint generated by default as identity primary key,
  profile_id bigint not null references public.profiles(id) on delete cascade,
  property_id bigint not null references public.properties(id) on delete cascade,
  created_at timestamptz not null default now(),
  unique (profile_id, property_id)
);

create table if not exists public.inquiries (
  id bigint generated by default as identity primary key,
  homeowner_id bigint not null references public.profiles(id) on delete cascade,
  property_id bigint not null references public.properties(id) on delete cascade,
  property_name text not null,
  property_image text,
  buyer_email text not null,
  message text not null,
  is_read boolean not null default false,
  created_at timestamptz not null default now()
);

create table if not exists public.support_tickets (
  id bigint generated by default as identity primary key,
  profile_id bigint references public.profiles(id) on delete set null,
  user_email text not null,
  subject text not null,
  description text not null,
  attachment_urls jsonb not null default '[]'::jsonb,
  status public.ticket_status not null default 'new',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.notification_preferences (
  profile_id bigint primary key references public.profiles(id) on delete cascade,
  push_notifications boolean not null default false,
  email_notifications boolean not null default false,
  in_app_notifications boolean not null default true,
  updated_at timestamptz not null default now()
);

-- ------------------------------------------------------------
-- Updated-at trigger
-- ------------------------------------------------------------

create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists set_profiles_updated_at on public.profiles;
create trigger set_profiles_updated_at
before update on public.profiles
for each row execute function public.set_updated_at();

drop trigger if exists set_properties_updated_at on public.properties;
create trigger set_properties_updated_at
before update on public.properties
for each row execute function public.set_updated_at();

create or replace function public.enforce_profile_integrity()
returns trigger
language plpgsql
security definer
as $$
begin
  -- Prevent non-admin users from escalating their role
  if new.role is distinct from old.role then
    if not exists (select 1 from public.profiles where auth_user_id = auth.uid() and role = 'admin') then
      new.role := old.role;
    end if;
  end if;

  -- Prevent tampering with auth binding or primary email
  new.auth_user_id := old.auth_user_id;
  new.email := old.email;
  
  return new;
end;
$$;

drop trigger if exists check_profile_integrity on public.profiles;
create trigger check_profile_integrity
before update on public.profiles
for each row execute function public.enforce_profile_integrity();

create or replace function public.enforce_property_integrity()
returns trigger
language plpgsql
security definer
as $$
begin
  if not exists (select 1 from public.profiles where auth_user_id = auth.uid() and role = 'admin') then
    if (new.status is distinct from old.status and new.status = 'approved') or
       (new.name is distinct from old.name) or
       (new.price is distinct from old.price) or
       (new.description is distinct from old.description) or
       (new.location is distinct from old.location) or
       (new.image_path is distinct from old.image_path) or
       (new.model_path is distinct from old.model_path) then
      new.status := 'pending';
    end if;
    new.is_featured := old.is_featured;
    new.homeowner_id := old.homeowner_id;
  end if;
  return new;
end;
$$;

drop trigger if exists check_property_integrity on public.properties;
create trigger check_property_integrity
before update on public.properties
for each row execute function public.enforce_property_integrity();

drop trigger if exists set_support_tickets_updated_at on public.support_tickets;
create trigger set_support_tickets_updated_at
before update on public.support_tickets
for each row execute function public.set_updated_at();

drop trigger if exists set_notification_preferences_updated_at on public.notification_preferences;
create trigger set_notification_preferences_updated_at
before update on public.notification_preferences
for each row execute function public.set_updated_at();

create or replace function public.handle_new_auth_user()
returns trigger
language plpgsql
security definer set search_path = ''
as $$
begin
  insert into public.profiles (
    auth_user_id, email, full_name, role, has_password
  )
  values (
    new.id,
    new.email,
    coalesce(new.raw_user_meta_data ->> 'full_name', new.raw_user_meta_data ->> 'name', 'User'),
    case new.raw_user_meta_data ->> 'role'
      when 'homeowner' then 'homeowner'::public.user_role
      else 'homebuyer'::public.user_role
    end,
    coalesce((new.raw_user_meta_data ->> 'has_password')::boolean, false)
  )
  on conflict (email) do update
  set auth_user_id = excluded.auth_user_id,
      full_name = coalesce(public.profiles.full_name, excluded.full_name),
      updated_at = now();
  return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
after insert on auth.users
for each row execute function public.handle_new_auth_user();

-- ------------------------------------------------------------
-- Storage
-- ------------------------------------------------------------

insert into storage.buckets (id, name, public)
values
  ('avatars', 'avatars', true),
  ('property-assets', 'property-assets', true),
  ('support-attachments', 'support-attachments', false)
on conflict (id) do update
set public = excluded.public;

-- Public read access for uploaded assets.
drop policy if exists "Public read avatars" on storage.objects;
create policy "Public read avatars"
on storage.objects
for select
using (bucket_id = 'avatars');

drop policy if exists "Public read property assets" on storage.objects;
create policy "Public read property assets"
on storage.objects
for select
using (bucket_id = 'property-assets');

drop policy if exists "Authenticated read support attachments" on storage.objects;
create policy "Authenticated read support attachments"
on storage.objects
for select
to authenticated
using (
  bucket_id = 'support-attachments'
  and (
    (storage.foldername(name))[1] = (select auth.uid()::text)
    or exists (select 1 from public.profiles where auth_user_id = auth.uid() and role = 'admin')
  )
);

-- Users write only inside a folder named after their Supabase user id.
drop policy if exists "Anon upload avatars" on storage.objects;
drop policy if exists "Authenticated upload avatars" on storage.objects;
create policy "Authenticated upload avatars"
on storage.objects
for insert
to authenticated
with check (
  bucket_id = 'avatars'
  and (storage.foldername(name))[1] = (select auth.uid()::text)
);

drop policy if exists "Anon update avatars" on storage.objects;
drop policy if exists "Authenticated update avatars" on storage.objects;
create policy "Authenticated update avatars"
on storage.objects
for update
to authenticated
using (
  bucket_id = 'avatars'
  and (storage.foldername(name))[1] = (select auth.uid()::text)
)
with check (
  bucket_id = 'avatars'
  and (storage.foldername(name))[1] = (select auth.uid()::text)
);

drop policy if exists "Anon delete avatars" on storage.objects;
drop policy if exists "Authenticated delete avatars" on storage.objects;
create policy "Authenticated delete avatars"
on storage.objects
for delete
to authenticated
using (
  bucket_id = 'avatars'
  and (storage.foldername(name))[1] = (select auth.uid()::text)
);

drop policy if exists "Anon upload property assets" on storage.objects;
drop policy if exists "Authenticated upload property assets" on storage.objects;
create policy "Authenticated upload property assets"
on storage.objects
for insert
to authenticated
with check (
  bucket_id = 'property-assets'
  and (storage.foldername(name))[1] = (select auth.uid()::text)
);

drop policy if exists "Anon update property assets" on storage.objects;
drop policy if exists "Authenticated update property assets" on storage.objects;
create policy "Authenticated update property assets"
on storage.objects
for update
to authenticated
using (
  bucket_id = 'property-assets'
  and (storage.foldername(name))[1] = (select auth.uid()::text)
)
with check (
  bucket_id = 'property-assets'
  and (storage.foldername(name))[1] = (select auth.uid()::text)
);

drop policy if exists "Anon delete property assets" on storage.objects;
drop policy if exists "Authenticated delete property assets" on storage.objects;
create policy "Authenticated delete property assets"
on storage.objects
for delete
to authenticated
using (
  bucket_id = 'property-assets'
  and (storage.foldername(name))[1] = (select auth.uid()::text)
);

drop policy if exists "Authenticated upload support attachments" on storage.objects;
create policy "Authenticated upload support attachments"
on storage.objects
for insert
to authenticated
with check (
  bucket_id = 'support-attachments'
  and (storage.foldername(name))[1] = (select auth.uid()::text)
);

drop policy if exists "Authenticated delete support attachments" on storage.objects;
create policy "Authenticated delete support attachments"
on storage.objects
for delete
to authenticated
using (
  bucket_id = 'support-attachments'
  and (storage.foldername(name))[1] = (select auth.uid()::text)
);

-- ------------------------------------------------------------
-- RLS
-- ------------------------------------------------------------

alter table public.profiles enable row level security;
alter table public.properties enable row level security;
alter table public.property_images enable row level security;
alter table public.favorites enable row level security;
alter table public.inquiries enable row level security;
alter table public.support_tickets enable row level security;
alter table public.notification_preferences enable row level security;

-- Profiles Policies
drop policy if exists "Profiles are readable" on public.profiles;
create policy "Profiles are readable" on public.profiles
for select to authenticated
using (
  auth.uid() = auth_user_id
  or exists (select 1 from public.profiles where auth_user_id = auth.uid() and role = 'admin')
);

drop policy if exists "Profiles are insertable" on public.profiles;
create policy "Profiles are insertable" on public.profiles
for insert to authenticated
with check (auth.uid() = auth_user_id);

drop policy if exists "Profiles are updatable" on public.profiles;
create policy "Profiles are updatable" on public.profiles
for update to authenticated
using (auth.uid() = auth_user_id)
with check (auth.uid() = auth_user_id);

-- Properties Policies
drop policy if exists "Properties are readable" on public.properties;
create policy "Properties are readable" on public.properties
for select
using (
  status = 'approved'
  or homeowner_id in (select id from public.profiles where auth_user_id = auth.uid())
  or exists (select 1 from public.profiles where auth_user_id = auth.uid() and role = 'admin')
);

drop policy if exists "Properties are insertable" on public.properties;
create policy "Properties are insertable" on public.properties
for insert to authenticated
with check (
  homeowner_id in (select id from public.profiles where auth_user_id = auth.uid() and role in ('homeowner', 'admin'))
);

drop policy if exists "Properties are updatable" on public.properties;
create policy "Properties are updatable" on public.properties
for update to authenticated
using (
  homeowner_id in (select id from public.profiles where auth_user_id = auth.uid())
  or exists (select 1 from public.profiles where auth_user_id = auth.uid() and role = 'admin')
)
with check (
  homeowner_id in (select id from public.profiles where auth_user_id = auth.uid())
  or exists (select 1 from public.profiles where auth_user_id = auth.uid() and role = 'admin')
);

drop policy if exists "Properties are deletable" on public.properties;
create policy "Properties are deletable" on public.properties
for delete to authenticated
using (
  homeowner_id in (select id from public.profiles where auth_user_id = auth.uid())
  or exists (select 1 from public.profiles where auth_user_id = auth.uid() and role = 'admin')
);

-- Property Images Policies
drop policy if exists "Property images are readable" on public.property_images;
create policy "Property images are readable" on public.property_images
for select
using (
  exists (
    select 1 from public.properties
    where public.properties.id = property_id
    and (
      status = 'approved'
      or homeowner_id in (select id from public.profiles where auth_user_id = auth.uid())
      or exists (select 1 from public.profiles where auth_user_id = auth.uid() and role = 'admin')
    )
  )
);

drop policy if exists "Property images are insertable" on public.property_images;
create policy "Property images are insertable" on public.property_images
for insert to authenticated
with check (
  exists (
    select 1 from public.properties
    where public.properties.id = property_id
    and (
      homeowner_id in (select id from public.profiles where auth_user_id = auth.uid())
      or exists (select 1 from public.profiles where auth_user_id = auth.uid() and role = 'admin')
    )
  )
);

drop policy if exists "Property images are updatable" on public.property_images;
create policy "Property images are updatable" on public.property_images
for update to authenticated
using (
  exists (
    select 1 from public.properties
    where public.properties.id = property_id
    and (
      homeowner_id in (select id from public.profiles where auth_user_id = auth.uid())
      or exists (select 1 from public.profiles where auth_user_id = auth.uid() and role = 'admin')
    )
  )
);

drop policy if exists "Property images are deletable" on public.property_images;
create policy "Property images are deletable" on public.property_images
for delete to authenticated
using (
  exists (
    select 1 from public.properties
    where public.properties.id = property_id
    and (
      homeowner_id in (select id from public.profiles where auth_user_id = auth.uid())
      or exists (select 1 from public.profiles where auth_user_id = auth.uid() and role = 'admin')
    )
  )
);

-- Favorites Policies
drop policy if exists "Favorites are readable" on public.favorites;
create policy "Favorites are readable" on public.favorites
for select to authenticated
using (profile_id in (select id from public.profiles where auth_user_id = auth.uid()));

drop policy if exists "Favorites are insertable" on public.favorites;
create policy "Favorites are insertable" on public.favorites
for insert to authenticated
with check (profile_id in (select id from public.profiles where auth_user_id = auth.uid()));

drop policy if exists "Favorites are deletable" on public.favorites;
create policy "Favorites are deletable" on public.favorites
for delete to authenticated
using (profile_id in (select id from public.profiles where auth_user_id = auth.uid()));

-- Inquiries Policies
drop policy if exists "Inquiries are readable" on public.inquiries;
create policy "Inquiries are readable" on public.inquiries
for select to authenticated
using (
  homeowner_id in (select id from public.profiles where auth_user_id = auth.uid())
  or buyer_email in (select email from public.profiles where auth_user_id = auth.uid())
  or exists (select 1 from public.profiles where auth_user_id = auth.uid() and role = 'admin')
);

drop policy if exists "Inquiries are insertable" on public.inquiries;
create policy "Inquiries are insertable" on public.inquiries
for insert to authenticated
with check (
  buyer_email in (select email from public.profiles where auth_user_id = auth.uid())
);

-- Support Tickets Policies
drop policy if exists "Support tickets are readable" on public.support_tickets;
create policy "Support tickets are readable" on public.support_tickets
for select to authenticated
using (
  profile_id in (select id from public.profiles where auth_user_id = auth.uid())
  or user_email in (select email from public.profiles where auth_user_id = auth.uid())
  or exists (select 1 from public.profiles where auth_user_id = auth.uid() and role = 'admin')
);

drop policy if exists "Support tickets are insertable" on public.support_tickets;
create policy "Support tickets are insertable" on public.support_tickets
for insert to authenticated
with check (
  profile_id in (select id from public.profiles where auth_user_id = auth.uid())
  or user_email in (select email from public.profiles where auth_user_id = auth.uid())
);

-- Notification Preferences Policies
drop policy if exists "Notification preferences are readable" on public.notification_preferences;
create policy "Notification preferences are readable" on public.notification_preferences
for select to authenticated
using (profile_id in (select id from public.profiles where auth_user_id = auth.uid()));

drop policy if exists "Notification preferences are insertable" on public.notification_preferences;
create policy "Notification preferences are insertable" on public.notification_preferences
for insert to authenticated
with check (profile_id in (select id from public.profiles where auth_user_id = auth.uid()));

drop policy if exists "Notification preferences are updatable" on public.notification_preferences;
create policy "Notification preferences are updatable" on public.notification_preferences
for update to authenticated
using (profile_id in (select id from public.profiles where auth_user_id = auth.uid()))
with check (profile_id in (select id from public.profiles where auth_user_id = auth.uid()));

-- ------------------------------------------------------------
-- Real-Time Conversations & 2-Way Messaging System
-- ------------------------------------------------------------

create table if not exists public.conversations (
  id bigint generated by default as identity primary key,
  property_id bigint not null references public.properties(id) on delete cascade,
  buyer_id bigint not null references public.profiles(id) on delete cascade,
  homeowner_id bigint not null references public.profiles(id) on delete cascade,
  last_message text not null default '',
  last_message_at timestamptz not null default now(),
  created_at timestamptz not null default now(),
  unique (property_id, buyer_id)
);

create table if not exists public.messages (
  id bigint generated by default as identity primary key,
  conversation_id bigint not null references public.conversations(id) on delete cascade,
  sender_id bigint not null references public.profiles(id) on delete cascade,
  message_text text not null,
  message_type text not null default 'text',
  viewing_date text,
  viewing_time text,
  viewing_mode text,
  viewing_status text default 'pending',
  is_read boolean not null default false,
  created_at timestamptz not null default now()
);

alter table public.conversations enable row level security;
alter table public.messages enable row level security;

-- Conversations Policies
drop policy if exists "Conversations are readable" on public.conversations;
create policy "Conversations are readable" on public.conversations
for select to authenticated
using (
  buyer_id in (select id from public.profiles where auth_user_id = auth.uid())
  or homeowner_id in (select id from public.profiles where auth_user_id = auth.uid())
  or exists (select 1 from public.profiles where auth_user_id = auth.uid() and role = 'admin')
);

drop policy if exists "Conversations are insertable" on public.conversations;
create policy "Conversations are insertable" on public.conversations
for insert to authenticated
with check (
  buyer_id in (select id from public.profiles where auth_user_id = auth.uid())
  or homeowner_id in (select id from public.profiles where auth_user_id = auth.uid())
);

drop policy if exists "Conversations are updatable" on public.conversations;
create policy "Conversations are updatable" on public.conversations
for update to authenticated
using (
  buyer_id in (select id from public.profiles where auth_user_id = auth.uid())
  or homeowner_id in (select id from public.profiles where auth_user_id = auth.uid())
);

-- Messages Policies
drop policy if exists "Messages are readable" on public.messages;
create policy "Messages are readable" on public.messages
for select to authenticated
using (
  exists (
    select 1 from public.conversations c
    where c.id = conversation_id
    and (
      c.buyer_id in (select id from public.profiles where auth_user_id = auth.uid())
      or c.homeowner_id in (select id from public.profiles where auth_user_id = auth.uid())
      or exists (select 1 from public.profiles where auth_user_id = auth.uid() and role = 'admin')
    )
  )
);

drop policy if exists "Messages are insertable" on public.messages;
create policy "Messages are insertable" on public.messages
for insert to authenticated
with check (
  sender_id in (select id from public.profiles where auth_user_id = auth.uid())
);

drop policy if exists "Messages are updatable" on public.messages;
create policy "Messages are updatable" on public.messages
for update to authenticated
using (
  exists (
    select 1 from public.conversations c
    where c.id = conversation_id
    and (
      c.buyer_id in (select id from public.profiles where auth_user_id = auth.uid())
      or c.homeowner_id in (select id from public.profiles where auth_user_id = auth.uid())
      or exists (select 1 from public.profiles where auth_user_id = auth.uid() and role = 'admin')
    )
  )
);
