-- ==============================================================================
-- Migration: 20260828010000_audit_logging.sql
-- Description: Provision immutable public.audit_logs table, RLS policies, and
--              harden messages RLS insert checks for SOC 2 & ISO 27001 compliance.
-- ==============================================================================

-- 1. Create audit_logs table
create table if not exists public.audit_logs (
  id bigint generated by default as identity primary key,
  actor_id bigint references public.profiles(id) on delete set null,
  actor_email text not null,
  actor_role public.user_role not null,
  action text not null,
  target_table text not null,
  target_id text not null,
  ip_address text,
  old_data jsonb,
  new_data jsonb,
  created_at timestamptz not null default now()
);

-- 2. Enable RLS
alter table public.audit_logs enable row level security;

-- 3. Policy: Admins can view audit logs
drop policy if exists "Admins can view audit logs" on public.audit_logs;
create policy "Admins can view audit logs"
  on public.audit_logs
  for select to authenticated
  using (
    exists (
      select 1 from public.profiles
      where auth_user_id = auth.uid() and role = 'admin'
    )
  );

-- 4. Policy: Authenticated users can insert audit logs for their own actions
drop policy if exists "Authenticated users can create audit logs" on public.audit_logs;
create policy "Authenticated users can create audit logs"
  on public.audit_logs
  for insert to authenticated
  with check (
    actor_id in (select id from public.profiles where auth_user_id = auth.uid())
    or exists (select 1 from public.profiles where auth_user_id = auth.uid() and role = 'admin')
  );

-- 5. Harden messages insert RLS policy (SEC-03)
drop policy if exists "Messages are insertable" on public.messages;
create policy "Messages are insertable" on public.messages
for insert to authenticated
with check (
  sender_id in (select id from public.profiles where auth_user_id = auth.uid())
  and exists (
    select 1 from public.conversations c
    where c.id = conversation_id
    and (
      c.buyer_id in (select id from public.profiles where auth_user_id = auth.uid())
      or c.homeowner_id in (select id from public.profiles where auth_user_id = auth.uid())
      or exists (select 1 from public.profiles where auth_user_id = auth.uid() and role = 'admin')
    )
  )
);
